### Test 1: Successful Patient Creation
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "John Doe",
  "dateOfBirth": "1985-04-12",
  "ssn": "120485-123A",
  "gender": "male",
  "occupation": "Software Engineer"
}

###

### Test 2: Failed Validation (Invalid Gender)
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Jane Doe",
  "dateOfBirth": "1990-08-24",
  "ssn": "240890-456B",
  "gender": "superman",
  "occupation": "Designer"
}



### Get all patients
GET http://localhost:3001/api/patients

### Get John McClane
GET http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9be15567